🏗 System Architecture
>Customer Side
1.Browse Products
2.Add Items to Cart
3.Place Order
4.Receive Confirmation
5.Track Order Status
6.Collect Packed Order
>Store Side
1.Receive Order Notification
2.Assign Staff
3.Pick Products
4.Pack Order
5.Mark as Ready
6.Handover to Customer
💻 Technology Stack
>Frontend
React.js
HTML5
CSS3
JavaScript
Bootstrap/Tailwind CSS
>Mobile Application
Flutter
>Backend
Node.js
Express.js
>Database
MongoDB
>Authentication
JWT Authentication
OAuth Integration
>Real-Time Communication
Socket.io
>Payment Integration
Razorpay
Stripe
>Cloud Services
Firebase
AWS
Cloud Services
Firebase
AWS
